const dummyData = {
  users: [
    {
      id: '1',
      name: 'John Doe',
      profileIconUrl: 'https://example.com/profile.jpg',
      email: 'john@example.com',
      password: 'password123',
      tasks: ['1', '2'],
    },
    {
      id: '2',
      name: 'Jane Smith',
      profileIconUrl: 'https://example.com/profile.jpg',
      email: 'jane@example.com',
      password: 'password123',
      tasks: ['3'],
    },
  ],
  tasks: [
    {
      id: '1',
      taskID: 'T1',
      title: 'Task 1',
      description: 'This is task 1',
      assignedTo: ['1'],
      status: 'PENDING',
      dueDate: '2022-12-31',
      assignedBy: '2',
      followedBy: ['1'],
      discussion: [
        {
          tags: ['tag1', 'tag2'],
          info: ['info1', 'info2'],
          taggedUser: ['1'],
        },
      ],
      acceptanceCriteria: 'Complete task 1',
      startDate: '2022-01-01',
      endDate: '2022-01-05',
      priority: ['HIGHEST'],
      valueArea: ['area1', 'area2'],
      logs: ['log1', 'log2'],
      links: ['link1', 'link2'],
      createdAt: '2022-01-01T00:00:00Z',
    },
    {
      id: '2',
      taskID: 'T2',
      title: 'Task 2',
      description: 'This is task 2',
      assignedTo: ['1'],
      status: 'IN_PROGRESS',
      dueDate: '2022-12-31',
      assignedBy: '2',
      followedBy: [],
      discussion: [],
      acceptanceCriteria: 'Complete task 2',
      startDate: '2022-01-06',
      endDate: '2022-01-10',
      priority: ['NORMAL'],
      valueArea: ['area2', 'area3'],
      logs: [],
      links: [],
      createdAt: '2022-01-02T00:00:00Z',
    },
    {
      id: '3',
      taskID: 'T3',
      title: 'Task 3',
      description: 'This is task 3',
      assignedTo: [],
      status: 'PENDING',
      dueDate: '2022-12-31',
      assignedBy: '2',
      followedBy: [],
      discussion: [],
      acceptanceCriteria: 'Complete task 3',
      startDate: null,
      endDate: null,
      priority: ['LOWEST'],
      valueArea: [],
      logs: [],
      links: [],
      createdAt: '2022-01-03T00:00:00Z',
    },
  ],
};

module.exports = dummyData;